name: Github Actions
on: [ push ]
jobs:
  TestApplication:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du repository
        uses: actions/checkout@v2
      - name: Liste des fichiers
        run: ls
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Faire les tests
        run: mvn test
